name: Compilar App para iOS (.ipa)

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Descargar Codigo
        uses: actions/checkout@v4

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Dar permisos de ejecucion a gradlew
        run: chmod +x ./gradlew

      # compilamos el framework de iOS en modo Release
      - name: Compilar framework de iOS
        run: ./gradlew :app:assembleReleaseIosSimulatorFramework

      # Creamos la carpeta Payload y empaquetamos el ejecutable en un archivo .ipa
      - name: Empaquetar ejecutable en archivo .ipa
        run: |
          mkdir -p Payload
          # Buscamos el ejecutable compilado y lo copiamos a la carpeta de empaquetado
          cp -r app/build/cocoapods/framework/ComposeApp.framework Payload/ || cp -r app/build/bin/iosSimulatorArm64/releaseFramework/ComposeApp.framework Payload/ || true
          # Comprimimos la carpeta en un archivo .ipa válido
          zip -r CapsulasGaribaldi.ipa Payload

      - name: Guardar instalable de iOS (.ipa)
        uses: actions/upload-artifact@v4
        with:
          name: App-iOS-Instalable-IPA
          path: CapsulasGaribaldi.ipa
