name: Compilar App para iOS

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Descargar Codigo
        uses: actions/checkout@v4

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Dar permisos de ejecucion a gradlew
        run: chmod +x ./gradlew

      # === USAMOS EL MÓDULO CORRECTO (:app) ===
      # Compilamos la tarea de iOS usando la arquitectura estándar del simulador
      - name: Compilar framework de iOS
        run: ./gradlew :app:assembleDebugIosSimulatorFramework

      - name: Guardar ejecutable compilado
        uses: actions/upload-artifact@v4
        with:
          name: App-iOS-Compilada
          # Guardamos la salida generada dentro de la carpeta build del módulo ':app'
          path: app/build/outputs/
