name: Desplegar Web App de Cafés

on:
  push:
    branches: [ main, master ]

# Esto le da explícitamente permiso de escritura al token de GitHub
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      # --- AQUÍ ESTÁ LA SOLUCIÓN ---
      - name: Dar permisos de ejecucion a gradlew
        run: chmod +x ./gradlew

      # Ahora ya no dará "Permission denied"
      - name: Compilar Web (Production Distribution)
        run: ./gradlew :app:wasmJsBrowserDistribution

      # Publicar la carpeta generada en gh-pages
      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/build/dist/wasmJs/productionExecutable
          branch: gh-pages
