name: Desplegar Web App de Cafés

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      # Tarea de Gradle que genera los archivos listos para la web
      - name: Compilar Web (Production Distribution)
        run: ./gradlew :app:wasmJsBrowserDistribution

      # Publica la carpeta generada directamente en la rama gh-pages
      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/build/dist/wasmJs/productionExecutable
          branch: gh-pages