name: Desplegar Web App de Cafés

on:
  push:
    branches: [ main, master ]

# Permisos necesarios para el despliegue con GitHub Actions
permissions:
  contents: read
  pages: write
  id-token: write

# Permite una sola ejecución simultánea para no pisar despliegues
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Dar permisos de ejecucion a gradlew
        run: chmod +x ./gradlew

      - name: Compilar Web (Production Distribution)
        run: ./gradlew :app:wasmJsBrowserDistribution

      - name: Subir artefacto de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Ruta a la carpeta que contiene el index.html
          path: 'app/build/dist/wasmJs/productionExecutable'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
